language: python
cache: pip
jobs:
  include:
    - name: "Python 3.9"
      dist: xenial
      python: '3.9-dev'
      install:
        - pip install "flake8>=3.8" -r requirements.txt
      script:
        - flake8 --count --max-line-length=120
        - python setup.py bdist_wheel sdist
    - name: "Python 3.8"
      dist: xenial
      python: '3.8'
      install:
        - pip install "flake8>=3.8" -r requirements.txt
      script:
        - flake8 --count --max-line-length=120
        - python setup.py bdist_wheel sdist
    - name: "Python 3.7"
      dist: xenial
      python: '3.7'
      install:
        - pip install "flake8>=3.8" -r requirements.txt
      script:
        - flake8 --count --max-line-length=120
        - python setup.py bdist_wheel sdist
    - name: "Python 3.6"
      dist: xenial
      python: '3.6'
      install:
        - pip install "flake8>=3.8" -r requirements.txt
      script:
        - flake8 --count --max-line-length=120
        - python setup.py bdist_wheel sdist
    - name: "Python 3.5"
      dist: xenial
      python: '3.5'
      install:
        - pip install "flake8>=3.8" -r requirements.txt
      script:
        - flake8 --count --max-line-length=120
        - python setup.py bdist_wheel sdist
    - name: "Python 3.4"
      dist: trusty
      python: '3.4'
      install:
        - pip install -I "flake8<=2.6" -r requirements.txt
      script:
        - flake8 --count --ignore=F401 --max-line-length=120 .
        - python setup.py bdist_wheel sdist
    - name: "Python 3.3"
      dist: trusty
      python: '3.3'
      install:
        - pip install -I "flake8<=2.6" -r requirements.txt
      script:
        - flake8 --count --ignore=F401 --max-line-length=120 .
        - python setup.py bdist_wheel sdist
    - name: "Python 2.7"
      dist: xenial
      python: '2.7'
      install:
        - pip install "flake8>=3.8" -r requirements.txt
      script:
        - flake8 --count --max-line-length=120
        - python setup.py bdist_wheel sdist
deploy:
  - provider: pypi
    user: dolfinus
    password:
      secure: I7xSC/V0Ob48x/OyMDX+r3ojFsZqEy4Gph0T5WyTVTgbEcDwI/nA3ZnRmSFM7dC9xbbN1lB1/mQ1pZcCAiCWIeSV3WHIjrUGGLunqFEXgDnbXFF8HsM9ZNKzrYt7407P4lz0NEX6SuD1yKTGv5MXtj23jMn/NsLtVTxgUZjbBjw3uNALoH1FKzRT/AETickghVLkPzrF6y7ov/6KThv6vSDMMxhHBUFJ+4uIaa8FoLBJFbKNsCbRjBLTZen4ud0VQr6SqMCwFuffcszPchqeyWec8/6dVe+v3ZbOOQIntecQynk2bapxolwCWNYyOjFQQ/NysP34G7N851YEATZGl+75cZhDxl4H7DJodedTs5vP7gura67zoTwKtIKLJgJnkEHUFGvQ5iTjrWsT7VElpddQUbBMhJM2yIpKG0RIeaPtuJP+gWFF5d1libaquiELpJ6iKsJia7yr2v45vIIGVvAYwrBNr3HlcnD5T+f97Z9+u2sibqnh7hCL7uwuzs+wsvewEh07VgnlHTc4W1LdvJO4ftatN9hcxeCEGz+gjWcykzzOWWBrYSv2AMmsmtiRJ1egEpynoPJxhx1/2WdqKi8GGG6cxocnG4wong635fqrMWtlUFkFYtSSlR+lYZOU7WXFeCuqexMx8Sn/0DKEF9rhbwDf4cDrRdgnPmIqkrc=
    on:
      tags: true
      distributions: sdist bdist_wheel
      repo: dolfinus/setuptools-git-versioning
    skip_cleanup: 'true'
    skip_existing: true
  - provider: releases
    api_key:
      secure: c5pZl7cYbwCK63923UdsJHKudrg/VE4hCosbg6SA5PpxRAusRu/gMmnSMB4KCUo6tiQZgDPOOtyLuqNpL5qVwLT6QAmzmr/CM+hYPl+zn2/bObGrnKkWvzurtZZgq8FUpS9+C7gwnHE3bZLQEDHdaaYmPoAFkhGDmDJ0MCX/J0ktr+IK4vwCJvc8ZjdnoLv5sw3XtOFjeO/B8kbCdGkSFJ/+YsPOpypdguCN+EMH5me5Vxiturq57mhPo3elDijHvsX06hmVeUATwOBFInXf3pummbC7rdqaJ4lrs/wReH4Ar0Vrjo1mAndB0MVKXhJ6nyHmsRLWVeI2crtTDqdnw29W2FHLVGiFWPNzNneZgRm1itgfKflzRtq7rM7439shixw5cNKI6EbhYtC2jiOBeK/I7zhQXa+cOK/H/PAumdy9e34HsElhHhGCFoINZYXzNW4AtVYzDl9GF1W4hXCbCB22h3V8sm1pGyywQ2cB80iLb4oRx9OdyWr/dbzlOim8u/lj0ORPMV70oRElHn4sCst35g5OP9goLlXpxHy0P9DzSwDe6mfZyB4/mXZ7lyI6RPgrN3A50dsIDoLMn06w2t4C4h37kGmU2VIBfu1lJR54YJQQViWeLaExid4/3jRajLKyB+KsS3+acwZwGnW5KYBKOg2QAdcsLfntGBKC4o0=
    file_glob: true
    file: dist/*
    on:
      repo: dolfinus/setuptools-git-versioning
      tags: true
    skip_cleanup: 'true'
