language: python
python:
  - "3.7"
install:
  - pip install flake8
script: 
  - flake8 --count
before_deploy: "python setup.py sdist bdist_wheel"
deploy:
  - provider: pypi
    user: "__token__"
    password:
      secure: "1PSWTFOHXIUJwHUXGHvHtzxKbiztnn0b5YMcojPvimCkOWywZrHPf+/ThQQCd3GcVhXpzsfKvxH7bnMBtXv9l5aXo0ufXrJQbam4OR9/OjVL/Yl0K+skglipQsf71PkzbGHURjwjhY3ARYIiX3vsYg+b5ta9V12IA3F3crSgbB0MkREIHDEV4MLGosEpPb2xDHvzNuaUWRc9gZbfAA8cVhKQy/6093ctKN1rsKAnk6YM4yHW/jvh4Dt466TBnSMrGYskefGDnRYeiPgt+FJNmCQ9xYI2qXaxFg79iLD0l+Q6ecBcnLBpYbbdJyd5fSiAwQmX61p9Tb31pVsyIdN5+1/2vmf4lciH6xINUnLg1hvA4ZY3yWToZjNLubo7jURW/jrSd2XDJQWL92s7u25xnmgfIqjKcyz5lNUVoq6Ig1uo9O2Uf2DBHniGRuzoHUGnduGV5zAN+68jv2KATFqScGtPTumBTfDlANEo/JHKLvfy0EpIR5hxuvj1X6OAaOrVUyDxtxStuCCZlNw9OBzxSq7K6cVUDtHmEbd5RvzhE5tboWviR0qCKJrK+t64/xEzw2U1pnpGfQfF9vLqMwT75qu2sUgR0TbdPIcblbQJQTGqONX/fTltstSuXBitIgjl7hmiq6/dbSjFcxBsqEGXuKRU6Up743CkROILwFretJw="
    on:
      tags: true
    distributions: "sdist bdist_wheel"
  - provider: releases
    api_key:
      secure: "QuH5WXrmNtbsLHtTwMz10tD+YlItKv16Gs1AsDsjAy2fVTufUarI6/HEtPm73N+xIXTScPgIEr1QLvAnGwAoYxm+i5KLuXasy0JCYFeKXXkE1oO77nCDHP9s2vN9/ptU14qDDG3TaE/FDSGa/83KNgCkpaDPHZaz5++peMYEReB1FQXHrueTBvwiFMNMSrFVGZvo3EuMbz9SwD0vJklNIAkrbaea/wRSktT3zX544/6eMt3j9Ntp7pJJ6gB/XJtHltgnvNT9p8SuSLfgRFEuS7jUDfbakvvAT9a5yvGwi8R6qhewq5vM8f8KiB6QmiHduQADFgQJ73XXfOqWFbwKz8H4V3LJDloSsEPfgXhlfT6LL6C2ZMcJ3PDPeXSgvX9xPo9ZYEr/t+eHr+ljI9tj/hlSm1AMMTJbrg8WUExWUQQj41F7azbhFQTSs4ZGAc8HXYp4XO4Y32ZuucyruF+EmnZDvbiLscHzLSuglGB5R9zpa+Dvs/RmBVbTZguVdtmAQRvFhjsgzTjWC774pvHMr/IlM+EqnjPV2lLMc58QCJmuadr923stxXpCobIu/Sf5QC75q8nesKPyZiGknCIEGfASOvYsNShxASFq0e6SkOLk4FpFbT1E6hZultxA64tSeDEhpzZTE6USJvHeF1ig8ZPRx0coqZStwj7fD9D5xEE="
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      tags: true
